apiVersion: v1
kind: Service

metadata:
  name: darshil-portfolio-service

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

spec:
  type: LoadBalancer

  loadBalancerClass: eks.amazonaws.com/nlb

  selector:
    app: darshil-portfolio

  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000